Repository simplabs/ember-template-lint-plugin-css-modules, pull requests merged in 2020-04, with the labels that each got.

#2 Add GitHub Actions setup for CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: internal

#3 Add `no-class` rule
  index.js
  rules/no-class.js
  rules/no-class.test.js
Labels: enhancement

#5 Add README and LICENSE files
  LICENSE.md
  README.md
Labels: documentation

#6 Add `.npmignore` file
  .npmignore
Labels: internal
